name: bubbles
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_localizations
  intl: ^0.17.0

  ## built_value: ^8.1.4
  built_value: ^8.2.3
  analyzer: ^4.1.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  freezed: ^2.0.3+1
  url_launcher: ^6.0.20

  #Voice Messages
  voice_message_package: 0.0.54
  syncfusion_flutter_core: ^19.1.63
  flutter_audio_recorder2: ^0.0.2
  syncfusion_flutter_sliders: 19.4.55

  # for Dependency injection
  get_it: ^7.2.0

  #Provider
  provider: ^5.0.0

  #Fonts
  google_fonts: ^3.0.1

  #logic
  flutter_fgbg: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  flutter_svg: ^1.0.3

  #social Login
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^5.3.1
  flutter_facebook_auth: ^4.3.4
  sign_in_with_apple: ^4.0.0
  flutter_signin_button: ^2.0.0


  # StateManagemant Packages
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  rxdart: ^0.27.1
  bloc: ^7.2.0
  json_serializable: ^6.1.5
  http: ^0.13.4
  flutter_riverpod: 1.0.3

  # http Packages
  cached_network_image: ^3.0.0
  dio:
  shared_preferences: ^2.0.6


  #string_extensions: ^0.6.2
  flutter_spinkit: ^5.0.0


  # UI packages
  dropdown_button2: ^1.4.0
  day_night_time_picker: ^1.0.1
  custom_marker: ^1.0.0
  move_to_background: ^1.0.2
  scroll_to_index: ^2.1.1
  swipe_to: ^1.0.2
  timeago: ^3.2.2
  responsive_sizer: ^3.0.8
  sizer: ^2.0.15
  modal_bottom_sheet: ^2.0.1
  qr_flutter: ^4.0.0
  conditional_questions: 2.0.0
  screenshot: ^1.2.3
  syncfusion_flutter_datepicker: ^19.1.59
  theme_manager: ^1.0.4
  bottom_sheet: ^3.0.0
  qr_code_scanner: ^0.7.0
  sliding_up_panel: ^2.0.0+1
  form_field_validator: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  google_maps_flutter: ^2.1.4
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  #font_awesome_flutter: 10.1.0
  flutter_rating_bar: ^4.0.0
  flutter_colorpicker: ^1.0.3
  image_picker: ^0.8.4+11
  flutter_switch: ^0.3.2
  showcaseview: ^1.1.0
  google_map_polyline_new: ^0.3.0+2
  internet_connection_checker: ^0.0.1+3
  flutter_slidable: ^1.2.0
  address_search_field: ^5.0.1

  ## notifications:
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.13
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6

  #Sync Contacts
  contacts_service: ^0.6.3
#  flutter_contacts: ^1.1.4
  share_plus: ^4.0.4
  flutter_sms: ^2.3.2
  flutter_email_sender: ^5.1.0
  flutter_share_me: ^1.3.0

  #Camera
  #  camera: ^0.9.4+4
  #google_ml_kit: ^0.7.3
  #native_screenshot: ^1.0.0

  #Logic packages
#  clipboard_manager: ^0.0.4



  #Voice Calls
  flutter_webrtc: ^0.8.5



  #socket io
  #socket_io_client: ^2.0.0-beta.2
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0
  ##nginx_le: ^8.2.6
  socket_io_client: 1.0.2

 #For Messaging Process
 # web_socket_channel: ^2.2.0



  #Permition handler
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  permission_handler: ^9.2.0
  path_provider: ^2.0.9



  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: 1.0.4
  build_runner: ^2.1.10
  built_value_generator: ^8.2.3


flutter:
#  generate : true
  uses-material-design: true

  assets:
    - Assets/images/
    - Assets/icons/
    - Assets/dark_map_style.json
    - Assets/light_map_style.json
    - lib/core/Language/lang/




  fonts:

  - family: SF Pro Display
    fonts:
      - asset: Assets/Fonts/SFPRODISPLAYBLACKITALIC.OTF


  - family: Helvetica
    fonts:
      - asset: Assets/Fonts/Helvetica.ttf

  - family: IBM Plex Sans
    fonts:
      - asset: Assets/Fonts/IBMPlexSans-Regular.ttf


  - family: SF Pro Text
    fonts:
      - asset: Assets/Fonts/FontsFree-Net-SFProText-Regular.ttf

  - family: Roboto Medium
    fonts:
      - asset: Assets/Fonts/Roboto-Medium.ttf

  - family: Red Hat Text
    fonts:
      - asset: Assets/Fonts/RedHatText-Regular.ttf

  - family: Red Hat Display
    fonts:
      - asset: Assets/Fonts/RedHatDisplay-Regular.ttf
    #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
